### PR TITLE
Gradle mods from tkirshboim

### PR DESCRIPTION
**Pull request by joebowbeer**
Contains tkirshboim's changes for building with Gradle, without the now-unnecessary btmidi change and with a few more tool versions updated to the current release. Disables fatal lint errors in some sample apps to avoid failing the build.

Please update README.md

### CODE REVIEW

**Comment by joebowbeer** [comment]
The README.md has now been updated.

The submodule pointers are probably messed up. These should be updated to the latest public revs.

**Comment by tkirshboim** [comment]
(continuing the discussion from https://github.com/joebowbeer/pd-for-android/pull/1)
The initializing the submodules works for me but when I run ```gradle assembleRelease``` I had ```NDK directory is not configured.```. I saw the ```getNdkBuildExecutablePath``` function in the PdCore build.gradle , but I couldn't figure out where this attribute comes from or how I could define it. I'm rarely working with the NDK, so maybe I'm missing something, but I couldn't find any documentation for that.
It would be useful to add maybe a line to the documentation explaining how to configure the NDK directory. What I did in the end was to add an ```ndk.dir``` variable to my ```local.properties``` but that's probably not the right way, because Android Studio warns me that this file will be overwritten..

Another small issue - Android Studio (1.2.1.1) is warning me about using the Android Gradle plugin version 1.2.0, as defined in the base ```build.gradle`` file:
```Warning: Using an obsolete version of the Gradle plugin (1.2.0); this can lead to layouts not rendering correctly.``` The suggested fix for that is to use version 1.2.3.

**Comment by joebowbeer** [comment]
I'm glad the submodules are OK now!

The NDK is configured by setting nkd.dir in local.properties in the project root, which is the most commonly chosen option, or setting the ANDROID_NDK_HOME environment variable.

The exception message can be made more helpful, and some documentation can be added, to specify for example which NDK version is recommended.

No problem updating the gradle plugin to 1.2.3. It is the current release, though this plugin is updated frequently. A plugin version is also configured in AndroidMidi, by the way, but perhaps this setting is ignored when AndroidMidi is built as a subproject.

In my testing, I use gradle command line or NetBeans with its Gradle plugin. Both can be used interchangeably. I've been concentrating on getting the gradle part right. In theory, this should be enough to keep Android Studio happy.

**Comment by joebowbeer** [comment]
FYI, the ndkDirectory is assigned by the findNdkLocation method in the Android gradle plugin's SdkHandler:

https://android.googlesource.com/platform/tools/base/+/master/build-system/gradle-core/src/main/groovy/com/android/build/gradle/internal/SdkHandler.java

**Comment by tkirshboim** [comment]
Thanks for the info. Setting ANDROID_NDK_HOME worked for me.
Now we only need to hope that someone reviews this pull request soon.. It could really simply things for Android developers that want to use pure data if all they need to do is add an .aar file as a dependency.

**Comment by joebowbeer** [comment]
I updated the gradle plugin version to what Android Studio expects, added a more informative error message when the NDK directory cannot be located, and updated README.md.

**Comment by joebowbeer** [comment]
This is working well for me so far. One thing I noticed when using the .aar is that AndroidMidi is not included, so we'll want to do the same for AndroidMidi?

**Comment by joebowbeer** [comment]
The default output of a library project is an .aar, so AndroidMidi is fine by default.

It will be very convenient for Android devs when these dependencies (PdCore and AndroidMidi) are available as versioned .aar files in public repos.

**Comment by joebowbeer** [comment]
In the most recent two commits I updated the submodules and consequently the libpd.so files.

These binaries were built with submodules:

646b1209d7e8b9eb8e5d21c6b3c94b07fcb3b2e PdCore/jni/libpd (0.8.3)
5f3930698569754c519f5b3e4cc7691223bc99a8 jni/opensl_stream (5f39306)
991b1835f1e3f39e33fa9cdda9312fab4ab80c79 pure-data (0.46-6-11-g991b183)
52a203909bab33e61ec8e132086ed5568748ec3 midi (heads/master)

**Comment by tkirshboim** [comment]
Tested with CLI and Android Studio. All example apps work fine.
closes #7 
closes #9 
closes #11 
closes #14

**Pull request merged**
