### PR TITLE
Renamed gradle project from PdCore to pd-core

### PR DESCRIPTION
**Pull request by tkirshboim**
workaround for the [gradle-bintray-plugin issue](https://github.com/bintray/gradle-bintray-plugin/issues/81) that caused the partial failure of the `bintrayUpload` task (see [this](https://github.com/libpd/pd-for-android/wiki/How-to-release-on-JCenter))

### CODE REVIEW

**Comment by tkirshboim** [comment]
Version 1 is release on JCenter. I'll update the README.md and create a Github release when this is merged.

**Comment by joebowbeer** [comment]
A fix for the gradle-bintray-plugin issue should be forthcoming. Should we wait for the fix?

**Comment by tkirshboim** [comment]
I think this solution is ok.
We don't know when the fix will be released and it's a small change that
will allow us to release more easily.

**Comment by tkirshboim** [comment]
Ok I see your point. Let's wait then and see if the bintray plugin is fixed soon and it works for us.
So we'll wait with merging this PR for now.

**Comment by joebowbeer** [comment]
The newly released gradle-bintray-plugin:1.6 should include the fix.

**Comment by tkirshboim** [comment]
Thanks. I'll give it a try in the next days.

**Comment by tkirshboim** [comment]
Closing because #42 fixes this issue without changing the gradle project names.

**Pull request closed without merging**
